version: '3'
services:
  db:
    container_name: db
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8081:8080"  # Kept the host port as 8081 for the keycloak service
    depends_on:
      - db

  todolist:
    container_name: todolist
    image: thecooldrop/todolist:latest
    ports:
      - "9080:8080"  # Kept the host port as 8080 for the todolist service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/keycloak
      SPRING_DATASOURCE_USERNAME: keycloak  # Replace with your actual username
      SPRING_DATASOURCE_PASSWORD: password  # Replace with your actual password
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
  
  frontned:
    container_name: frontned
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
     - "8080:80"

volumes:
  db_data: